#!/usr/bin/env bash
#
# Build the screener and publish it: hashed assets to a directory nginx can read,
# the Nitro server restarted behind it.
#
#   ./deploy/build_and_deploy.sh
#
# Safe to re-run. Does the whole thing or nothing much: the asset sync happens only
# after a successful build, and the service is restarted only after the sync.
#
# WHY THE ASSETS ARE COPIED OUT OF THE REPO
#   /home/dev is drwxr-x---, so www-data cannot traverse it, and nginx cannot read
#   .output/public where it sits. The alternatives were to loosen the home directory
#   for everyone or to publish the assets somewhere conventional. This does the second.
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
STATIC_ROOT="/var/www/screener"
export PATH="$HOME/.local/tools/node/bin:$PATH"

cd "$REPO"

echo "==> building"
npx nuxt build

[ -d .output/public/_nuxt ] || { echo "!! .output/public/_nuxt missing after build" >&2; exit 1; }

echo "==> publishing static assets to ${STATIC_ROOT}"
sudo mkdir -p "$STATIC_ROOT"
# --delete removes assets from builds that no longer exist. Safe because every file
# here is content-hashed and regenerated by the build; nothing else lives in this tree.
sudo rsync -a --delete .output/public/ "$STATIC_ROOT/"
sudo chown -R root:www-data "$STATIC_ROOT"
sudo find "$STATIC_ROOT" -type d -exec chmod 755 {} +
sudo find "$STATIC_ROOT" -type f -exec chmod 644 {} +
echo "    $(find "$STATIC_ROOT" -type f | wc -l) files, $(du -sh "$STATIC_ROOT" | cut -f1)"

if systemctl list-unit-files screener.service >/dev/null 2>&1 && \
   [ -f /etc/systemd/system/screener.service ]; then
  echo "==> restarting screener.service"
  sudo systemctl restart screener
  sleep 2
  systemctl is-active --quiet screener || { echo "!! screener.service did not come up" >&2; journalctl -u screener -n 20 --no-pager; exit 1; }
  code=$(curl -s -o /dev/null -w '%{http_code}' 127.0.0.1:3000/ || true)
  echo "    service up, / returns HTTP ${code}"
else
  cat <<'MSG'
==> screener.service is not installed yet. Once:
      sudo cp deploy/screener.service /etc/systemd/system/
      sudo systemctl daemon-reload && sudo systemctl enable --now screener
MSG
fi

echo "DONE"
