#!/usr/bin/env bash
#
# The one command. Builds the screener, publishes it, restarts what needs
# restarting, then checks the whole chain and says which link is broken.
#
#   ./deploy/deploy.sh
#
# Safe to re-run at any time. Nothing is published until the build succeeds and
# nothing is restarted until the publish succeeds, so a failed run leaves the
# site exactly as it was.
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
STATIC_ROOT="/var/www/screener"
UPSTREAM="127.0.0.1:3000"
HOSTNAME_PUBLIC="${SCREENER_HOSTNAME:-stockey.japlin.com}"
export PATH="$HOME/.local/tools/node/bin:$PATH"
cd "$REPO"

ok()   { printf '  \033[32mok\033[0m    %s\n' "$1"; }
warn() { printf '  \033[33mwarn\033[0m  %s\n' "$1"; }
bad()  { printf '  \033[31mFAIL\033[0m  %s\n' "$1"; }

echo "==> building"
npx nuxt build
[ -d .output/public/_nuxt ] || { bad ".output/public/_nuxt missing after build"; exit 1; }
[ -f .output/server/index.mjs ] || { bad ".output/server/index.mjs missing after build"; exit 1; }

echo "==> publishing assets to ${STATIC_ROOT}"
sudo mkdir -p "$STATIC_ROOT"
# --delete drops assets from older builds. Safe: every file here is content-hashed
# and regenerated by the build, and nothing else lives in this tree.
sudo rsync -a --delete .output/public/ "$STATIC_ROOT/"
sudo chown -R root:www-data "$STATIC_ROOT"
sudo find "$STATIC_ROOT" -type d -exec chmod 755 {} +
sudo find "$STATIC_ROOT" -type f -exec chmod 644 {} +
ok "$(find "$STATIC_ROOT" -type f | wc -l) files, $(du -sh "$STATIC_ROOT" | cut -f1)"

echo "==> restarting the app"
if [ ! -f /etc/systemd/system/screener.service ]; then
  sudo cp deploy/screener.service /etc/systemd/system/
  sudo systemctl daemon-reload
  sudo systemctl enable screener >/dev/null 2>&1
  ok "installed screener.service"
fi
sudo systemctl restart screener
for i in $(seq 1 15); do
  sleep 1
  [ "$(curl -s -o /dev/null -w '%{http_code}' "http://${UPSTREAM}/" || true)" = "200" ] && break
done

echo "==> reloading nginx"
if [ -e /etc/nginx/sites-enabled/screener ]; then
  sudo nginx -t >/dev/null 2>&1 && sudo systemctl reload nginx && ok "reloaded" \
    || { bad "nginx config test failed — NOT reloaded, the old config is still serving"; sudo nginx -t; exit 1; }
else
  warn "no screener site in nginx yet. Once:"
  echo "        sudo ./deploy/setup_nginx_proxy.sh <username> --static-root ${STATIC_ROOT}"
fi

# ---------------------------------------------------------------- the chain
# Checked from the inside out, so the first failure is the broken link rather
# than a symptom of one further down.
echo
echo "==> checking the chain"

systemctl is-active --quiet screener \
  && ok "app service running" || bad "screener.service is not running (journalctl -u screener)"

app=$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 "http://${UPSTREAM}/" || echo 000)
[ "$app" = "200" ] && ok "app answers on ${UPSTREAM}" || bad "app returned ${app} on ${UPSTREAM}"

gate=$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 http://127.0.0.1/ || echo 000)
case "$gate" in
  401) ok "nginx up, basic auth is gating it" ;;
  200) warn "nginx answered 200 WITHOUT credentials — the auth gate is not applied" ;;
  *)   bad "nginx returned ${gate} locally" ;;
esac

# A hashed asset the freshly built page actually references, fetched through nginx:
# this is what proves the static root is wired up rather than 404ing.
asset=$(curl -s --max-time 10 "http://${UPSTREAM}/" | grep -oE '/_nuxt/[A-Za-z0-9._-]+\.js' | head -1 || true)
if [ -n "$asset" ]; then
  a=$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 "http://127.0.0.1${asset}" || echo 000)
  case "$a" in
    401) ok "static assets served by nginx (401 = behind the gate, as intended)" ;;
    404) bad "nginx 404s ${asset} — is the site configured with --static-root ${STATIC_ROOT}?" ;;
    *)   warn "static asset check returned ${a}" ;;
  esac
fi

pub4=$(curl -s -o /dev/null -w '%{http_code}' --max-time 8 "http://$(curl -s --max-time 8 https://api.ipify.org)/" || echo 000)
[ "$pub4" = "401" ] && ok "origin answers on its own public IPv4" \
  || warn "origin returned ${pub4} on its public IPv4"

echo
echo "==> checking ${HOSTNAME_PUBLIC} (through Cloudflare)"
pub=$(curl -s -o /dev/null -w '%{http_code}' --max-time 25 "https://${HOSTNAME_PUBLIC}/" || echo 000)
case "$pub" in
  401) ok "LIVE — the site is up and asking for the password" ;;
  200) warn "200 without credentials: Cloudflare may be serving a cached page" ;;
  521|522|523)
    bad "Cloudflare cannot reach this box (HTTP ${pub})."
    echo
    echo "      Everything above this line passed, so the origin is fine and the"
    echo "      problem is the DNS record. In the Cloudflare dashboard, the record for"
    echo "      ${HOSTNAME_PUBLIC} must point at THIS machine:"
    echo
    echo "          A     ${HOSTNAME_PUBLIC}  ->  $(curl -s --max-time 8 https://api.ipify.org)     (proxied)"
    echo "          AAAA  ${HOSTNAME_PUBLIC}  ->  $(ip -6 addr show scope global | grep -oE '2[0-9a-f:]+::[0-9a-f]+' | head -1)   (proxied, or delete it)"
    echo
    echo "      A stale AAAA is the usual cause: Cloudflare prefers IPv6, so a wrong"
    echo "      AAAA times out even when the A record is perfect."
    ;;
  530) bad "HTTP 530 — the hostname is not attached to a Cloudflare zone" ;;
  000) bad "no response at all — DNS may not have propagated yet" ;;
  *)   warn "unexpected status ${pub}" ;;
esac
echo
echo "DONE"
