universes:
  - screener_slug: train-largecap-liquid
    screener_name: TRAIN_LARGECAP_LIQUID
    query_name: Train Largecap Liquid
    query_text: |
      Market capitalization > 20000 AND
      Current price > 50

  - screener_slug: train-midcap-liquid
    screener_name: TRAIN_MIDCAP_LIQUID
    query_name: Train Midcap Liquid
    query_text: |
      Market capitalization > 5000 AND
      Market capitalization < 20000 AND
      Current price > 30

  - screener_slug: train-event-sensitive
    screener_name: TRAIN_EVENT_SENSITIVE
    query_name: Train Event Sensitive
    query_text: |
      Market capitalization > 3000 AND
      Price to earning > 0 AND
      Return on capital employed > 8% AND
      Current price > 20
